# Use the official PHP 8.4.4 image as the base
FROM php:8.4.4-fpm

# Install necessary PHP extensions
RUN docker-php-ext-install bcmath intl

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Install Composer
# RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set the working directory
WORKDIR /var/www/html

# Copy application files
COPY . .

# Install PHP dependencies
RUN composer install --no-dev --optimize-autoloader

# Expose the port the service will run on
EXPOSE 8000

# Start the PHP-FPM server
CMD ["php-fpm"]

# Start Laravel application
CMD php artisan migrate --force && php artisan serve --host 0.0.0.0 --port 8000
 








