services:
  - type: web
    name: firefly-iii
    runtime: docker
    repo: https://github.com/Leslie-23/firefly-iii
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService: firefly-db
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: firefly
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: yourpassword
