services:
  - type: web
    name: firefly-iii
    runtime: docker
    repo: https://github.com/Leslie-23/firefly-iii
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService: dpg-cuqiqmjtq21c73812af0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: firefly_db_jqow
      - key: DB_USERNAME
        value: firefly_db_jqow_user
      - key: DB_PASSWORD
        value: YjKLUDsN9B5eDGt7mr9ZNgyMm6BaMjx4
